# 服务端口
server:
  port: 6006

spring:
  # 环境设置
  profiles:
    active: dev
  # 服务名
  application:
    name: service-ucenter
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.166.128:3306/cloud_blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置springCloud
  cloud:
    # 配置nacos注册中心
    nacos:
      discovery:
        server-addr: localhost:8848
  # redis配置
  redis:
    host: 192.168.166.128
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  # 邮件配置
  mail:
    host: smtp.163.com
    username: muaker@163.com
    password: KBYCVXXLRZGMZNJS
    port: 25
    protocol: smtp
    default-encoding: utf-8
    subject: 小码客个人博客网站

# mybatis配置
mybatis-plus:
  configuration:
    # 开启mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mapper.xml文件的路径
  mapper-locations: classpath:com/mark/ucenter/mapper/xml/*.xml

# 第三方登录配置
third:
  login:
    # GitHub登录配置
    github:
      clientId: 59893b9eaeab2f071f91
      secret: 469abc49468b0038922760f9ea751def5cea2b78
      redirectUrl: http://192.168.166.128:600/api/ucenter/login/github/callback
    # Gitee登录配置
    gitee:
      clientId: 942924a45398a460db7020fa5524c6b0e956213b55843eff3fe111836c8f27f1
      secret: 026a320312744ddb8259d576a429a5a6b3e7521c8539807844f12fc04d03cbf8
      redirectUrlCode: http://192.168.166.128:600/api/ucenter/login/gitee/callback
      redirectUrlToken: http://192.168.166.128:600/api/ucenter/login/gitee/callback/token
